"""new fields in user model

Revision ID: 554d6df645cc
Revises: 96da9145809a
Create Date: 2019-01-28 15:18:52.741182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554d6df645cc'
down_revision = '96da9145809a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
